export const PROJECT_CATEGORIES = [
  'AI Tools',
  'Security',
  'Infrastructure',
  'DeFi',
  'Research',
  'AI Agent',
  'Gaming and Virtual Worlds',
  'NFTs',
  'Governance',
  'Marketplaces',
  'Identity',
  'Healthcare',
  'Education',
  'Sustainability and Climate',
  'Social Platforms',
  'Supply Chain',
  'Generated Content',
  'Tokenomics',
  'Analytics',
  'Edge Computing and IoT',
  'Interoperability',
  'Privacy',
  'Marketing and Advertising',
  'Fraud Detection',
  'Personal Assistants',
  'Data Monetization'
] as const;