// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtjnknpfeonpzlphsraa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0am5rbnBmZW9ucHpscGhzcmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MDMzNjYsImV4cCI6MjA1MzM3OTM2Nn0.lvLNbOJQc7-yrSqrtFwP3sYIjqZ6qDZ1BX4D5TaeIkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);